export const TI4_FACTIONS = [
  'The Arborec',
  'The Argent Flight',
  'The Barony of Letnev',
  'The Clan of Saar',
  'The Embers of Muaat',
  'The Emirates of Hacan',
  'The Federation of Sol',
  'The Ghosts of Creuss',
  'The L1Z1X Mindnet',
  'The Mentak Coalition',
  'The Naalu Collective',
  'The Nekro Virus',
  'Sardakk N\'orr',
  'The Universities of Jol-Nar',
  'The Winnu',
  'The Xxcha Kingdom',
  'The Yin Brotherhood',
  'The Yssaril Tribes',
  // Prophecy of Kings expansions
  'The Council Keleres',
  'The Empyrean',
  'The Mahact Gene-Sorcerers',
  'The Naaz-Rokha Alliance',
  'The Nomad',
  'The Titans of Ul',
  'The Vuil\'raith Cabal',
] as const;
